import type { AdminSection } from '../models/admin.models';

export const ADMIN_STORAGE_KEYS = {
  accessToken: 'shopkeeperAdminToken',
  user: 'shopkeeperAdminUser',
} as const;

export const ADMIN_API_ENDPOINTS = {
  login: 'admin/login',
  forgotPassword: 'auth/forgot-password',
  resetPassword: 'auth/reset-password',
  products: 'admin/products',
  categories: 'admin/categories',
  orders: 'admin/orders',
  deliveryAgents: 'admin/delivery-agents',
  section: {
    overview: (period: string) => `admin/analytics?period=${period}`,
    orders: (page: number, limit: number) => `admin/orders?page=${page}&limit=${limit}`,
    products: (page: number, limit: number) => `admin/products?page=${page}&limit=${limit}`,
    categories: 'admin/categories',
    customers: (page: number, limit: number) => `admin/users?page=${page}&limit=${limit}`,
    delivery: 'admin/delivery-agents',
    payments: (page: number, limit: number) => `payments/admin/transactions?page=${page}&limit=${limit}`,
  },
} as const;

export const ADMIN_CONFIG = {
  minimumPasswordLength: 8,
  defaultAnalyticsPeriod: '30d',
  defaultPage: 1,
  defaultPageSize: 100,
  minorCurrencyUnitsPerMajor: 100,
} as const;

export const ADMIN_ORDER_STATUSES = [
  'pending',
  'confirmed',
  'processing',
  'shipped',
  'delivered',
  'cancelled',
  'refunded',
] as const;

export const ADMIN_APP_TEXT = {
  appName: 'Shopkeeper Admin',
  description: 'Manage shop operations, inventory, orders, customers, and payments.',
  brandName: 'SHOPKEEPER',
  sections: {
    overview: 'Overview',
    orders: 'Orders',
    products: 'Inventory',
    categories: 'Categories',
    customers: 'Customers',
    delivery: 'Delivery team',
    payments: 'Payments',
  },
  login: {
    eyebrow: 'OPERATIONS CONSOLE',
    headline: 'Run the shop.',
    headlineSecondLine: 'Keep every order moving.',
    description: 'Inventory, fulfillment, customers, and payments in one place.',
    footnote: 'Authorized administrators only',
    signInEyebrow: 'ADMIN SIGN IN',
    welcome: 'Welcome back',
    prompt: 'Use your administrator account to continue.',
    email: 'Email address',
    password: 'Password',
    signingIn: 'Signing in...',
    signIn: 'Sign in',
    forgotPassword: 'Forgot password?',
  },
  recovery: {
    back: '← Back to sign in',
    security: 'ACCOUNT SECURITY',
    choosePassword: 'Choose a new password',
    description: 'Use at least {{length}} characters. This reset link can only be used once.',
    invalidLink: 'This reset link is invalid or expired. Request a new link to continue.',
    requestNewLink: 'Request a new link',
    returnToSignIn: 'Return to sign in',
    accountRecovery: 'ACCOUNT RECOVERY',
    forgotPassword: 'Forgot your password?',
    requestDescription: 'Enter your administrator email. If it matches, we’ll send a secure reset link.',
    email: 'Email address',
    openDevelopmentLink: 'Open development reset link',
    sending: 'Sending...',
    sendResetLink: 'Send reset link',
    requestFallback: 'If an account exists, a reset link has been sent.',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    updating: 'Updating...',
    updatePassword: 'Update password',
    emailRequired: 'Enter the email address on your administrator account.',
    minimumPassword: 'Use at least {{length}} characters for your new password.',
    passwordsMismatch: 'The passwords do not match.',
  },
  workspace: {
    caption: 'WORKSPACE',
    administrator: 'Administrator',
    defaultName: 'admin',
    signOut: 'Sign out',
    shopOperations: 'Shop operations',
    apiConnected: 'API connected',
    overview: 'OVERVIEW / LAST 30 DAYS',
    greeting: 'Good day, {{name}}',
    overviewDescription: 'A live view of orders, inventory, and customer activity.',
    refresh: 'Refresh',
    deliveredRevenue: 'Delivered revenue',
    deliveredOrdersLast30Days: 'Delivered orders, last 30 days',
    orders: 'Orders',
    placedLast30Days: 'Placed in the last 30 days',
    activeProducts: 'Active products',
    availableCatalog: 'Available in the catalog',
    customers: 'Customers',
    accountsLast30Days: 'Accounts created in the last 30 days',
    recentOrders: 'Recent orders',
    latestActivity: 'Latest activity',
    allOrders: 'All orders',
    topProducts: 'Top products',
    byUnitsSold: 'By units sold',
    inventory: 'Inventory',
    noRecentOrders: 'No recent orders.',
    noSalesData: 'No sales data yet.',
    loadingActivity: 'Loading shop activity...',
    noOverviewData: 'No overview data is available.',
    customer: 'Customer',
    order: 'Order',
    status: 'Status',
    total: 'Total',
    stockCount: '{{count}} in stock',
    noOrders: 'No orders found.',
  },
  orders: {
    eyebrow: 'FULFILLMENT',
    title: 'Orders',
    description: 'Review purchases and move each order through fulfillment.',
    refresh: 'Refresh orders',
    all: 'All orders',
    loaded: '{{count}} loaded',
    search: 'Search order or customer',
    order: 'Order',
    placed: 'Placed',
    customer: 'Customer',
    items: 'Items',
    payment: 'Payment',
    total: 'Total',
    status: 'Status',
    empty: 'No orders match this search.',
  },
  products: {
    eyebrow: 'CATALOG',
    inventory: 'Inventory',
    description: 'Manage product information, pricing, and stock.',
    add: 'Add product',
    products: 'Products',
    loaded: '{{count}} loaded',
    search: 'Search products',
    product: 'Product',
    sku: 'SKU',
    category: 'Category',
    price: 'Price',
    stock: 'Stock',
    availability: 'Availability',
    active: 'Active',
    archived: 'Archived',
    edit: 'Edit',
    archive: 'Archive',
    empty: 'No products match this search.',
    descriptionField: 'Description',
    originalPrice: 'Original price',
    selectCategory: 'Select category',
    imageUrls: 'Image URLs',
    imageUrlsPlaceholder: 'https://... (comma separated)',
    productIsActive: 'Product is active',
    cancel: 'Cancel',
    saving: 'Saving...',
    save: 'Save product',
  },
  categories: {
    eyebrow: 'CATALOG STRUCTURE',
    title: 'Categories',
    description: 'Organize products and control which categories appear in the shop.',
    add: 'Add category',
    category: 'Category',
    descriptionColumn: 'Description',
    sortOrder: 'Sort order',
    visibility: 'Visibility',
    visible: 'Visible',
    hidden: 'Hidden',
    edit: 'Edit',
    hide: 'Hide',
    show: 'Show',
    empty: 'No categories found.',
  },
  customers: {
    eyebrow: 'CUSTOMER ACCOUNTS',
    title: 'Customers',
    description: 'Review registered accounts and verification status.',
    refresh: 'Refresh',
    directory: 'Customer directory',
    loaded: '{{count}} loaded',
    search: 'Search name or email',
    customer: 'Customer',
    email: 'Email',
    phone: 'Phone',
    joined: 'Joined',
    verification: 'Verification',
    verified: 'Verified',
    pending: 'Pending',
    empty: 'No customers match this search.',
  },
  delivery: {
    eyebrow: 'FULFILLMENT TEAM',
    title: 'Delivery team',
    description: 'Create rider accounts and review delivery activity.',
    addPartner: 'Add delivery partner',
    partner: 'Partner',
    email: 'Email',
    phone: 'Phone',
    vehicle: 'Vehicle',
    deliveries: 'Deliveries',
    earnings: 'Earnings',
    availability: 'Availability',
    available: 'Available',
    onDelivery: 'On delivery',
    empty: 'No delivery partners found.',
  },
  payments: {
    eyebrow: 'SETTLEMENTS',
    title: 'Payment activity',
    description: 'Provider attempts, COD collections, failures, and refunds.',
    refresh: 'Refresh',
    reference: 'Reference',
    order: 'Order',
    provider: 'Provider',
    method: 'Method',
    status: 'Status',
    amount: 'Amount',
    recorded: 'Recorded',
    empty: 'No payment transactions found.',
  },
  modal: {
    catalog: 'CATALOG',
    catalogStructure: 'CATALOG STRUCTURE',
    editProduct: 'Edit product',
    addProduct: 'Add product',
    close: 'Close',
    name: 'Name',
    brand: 'Brand',
    price: 'Price (INR)',
    stock: 'Stock',
    category: 'Category',
    categorySelect: 'Select category',
    imageUrls: 'Image URLs',
    imageUrlsPlaceholder: 'https://... (comma separated)',
    imageUrl: 'Image URL',
    visibleInShop: 'in shop',
    description: 'Description',
    activeProduct: 'Product is active',
    cancel: 'Cancel',
    saving: 'Saving...',
    saveProduct: 'Save product',
    editCategory: 'Edit category',
    addCategory: 'Add category',
    saveCategory: 'Save category',
    save: 'Save',
    deliveryPartner: 'DELIVERY PARTNER',
    createAccount: 'Create delivery account',
    vehicleType: 'Vehicle type',
    bike: 'Bike',
    car: 'Car',
    truck: 'Truck',
    vehicleNumber: 'Vehicle number',
    licenseNumber: 'License number',
    create: 'Create',
    creating: 'Creating...',
  },
  messages: {
    overview: 'Overview',
    categoryFallback: 'Category',
    productSaved: 'Product saved.',
    productArchived: 'Product archived.',
    categorySaved: 'Category saved.',
    deliveryAccountCreated: 'Delivery account created.',
    categoryHidden: 'Category hidden.',
    categoryVisible: 'Category made visible.',
    saveFailed: 'The change could not be saved.',
    archiveConfirm: 'Archive {{name}}? It will no longer appear in the shop.',
    orderUpdated: 'Order {{order}} updated.',
    accountAccessRequired: 'This account does not have administrator access.',
    unableSignIn: 'Unable to sign in. Check the administrator credentials.',
    unableLoadSection: 'Unable to load {{section}}.',
    unableRequestReset: 'Unable to request a password reset.',
    invalidResetLink: 'This reset link is invalid or expired.',
  },
} as const;

export const ADMIN_SECTIONS: ReadonlyArray<{ id: AdminSection; label: string; mark: string }> = [
  { id: 'overview', label: ADMIN_APP_TEXT.sections.overview, mark: 'OV' },
  { id: 'orders', label: ADMIN_APP_TEXT.sections.orders, mark: 'OR' },
  { id: 'products', label: ADMIN_APP_TEXT.sections.products, mark: 'IN' },
  { id: 'categories', label: ADMIN_APP_TEXT.sections.categories, mark: 'CA' },
  { id: 'customers', label: ADMIN_APP_TEXT.sections.customers, mark: 'CU' },
  { id: 'delivery', label: ADMIN_APP_TEXT.sections.delivery, mark: 'DT' },
  { id: 'payments', label: ADMIN_APP_TEXT.sections.payments, mark: 'PY' },
];
